# this file contains deployment configuration for kraken btcusd orderbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-btcusd-orderbook
  labels:
    app: btcusd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btcusd
  template:
    metadata:
      labels:
        app: btcusd
    spec:
      containers:
        - name: kraken-btcusd-orderbook-container
          image: 501424711349.dkr.ecr.us-east-1.amazonaws.com/kraken-btcusd-orderbook
          env:
            - name: WRITERHOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: WRITERHOST
            - name: READERHOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: READERHOST
            - name: SYMBOL
              value: "BTC/USD"
            - name: STREAM_NAME
              value: "kraken-orderbook"
            - name: EXECUTE_IN_DOCKER
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: EXECUTE_IN_DOCKER
            - name: REDISPORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDISPORT

          imagePullPolicy: Always
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: kraken-btcusd-orderbook-service
spec:
  selector:
    app: btcusd
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
